# (APPENDIX) Appendix {-}

# Bibliography {#bibliography}

## Books

[**Advanced High School Statistics 3rd Ed**](https://www.openintro.org/book/ahss/), Diez et al: A detailed and rigorous introduction to statistics that would suit advanced high school and undergraduate university students. The theory and applications of statistics are covered from collecting data through to inference and statistical tests. The book contains numerous exercise and examples to help students develop their knowledge and skills.

[**Introductory Statistics, Shafer and Zhang**](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Introductory_Statistics_(Shafer_and_Zhang)): Hosted on [LibreTexts](https://libretexts.org/), this is another thorough but accessible introduction to the theory and practice of statistics. The book begins with a detailed explanation of descriptive statistics and probability, and random variables. Later chapters cover sampling distributions, hypotheses, and hypothesis testing.

[Learning Statistics with R - A tutorial for Psychology Students and other Beginners](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)), Navarro, D:

## Articles


## Websites

[**Australian Bureau of Statistics "Statistical Terms and Concepts"**](https://www.abs.gov.au/statistics/understanding-statistics/statistical-terms-and-concepts): A comprehensive glossary of statistical terms. Click the terms for detailed explanations.


