# Statistical Tests {#stat_tests}

>**Learning Objectives**  
To understand the process of sampling  
To select, apply, and interpret common statistical tests  
To understand p-values and statistical signifiance  
To create and interpret confidence intervals

## Sampling
* Sampling should be done with replacement
* Often not with replacement in practice - OK for large enough population
* Sources of dependency - time, space
* Common sampling mistakes

## Common Statistical Tests

Purpose|Dependent \n Variable|Independent \n Variable|Parametric \n Test \n (normal)|Non-parametric \n Test \n (skewed or ordinal)
-------|------------------|--------------------|---------------|-------------------
Comparing means of two independent groups|Discrete or continuous|Nominal (two groups)|Independent T-test|Mann-Whitney Test; Wilcoxon Rank Sum
Comparing means of two paired (before / after) groups|Discrete or continuous|Ordinal (two groups)|Paired T-test|Wilcoxon Signed Rank Test
Comparing Means of 3+ independent groups|Discrete or continuous|Nominal (three or more groups)|One-way ANOVA|Kruskal-Wallis Test

### Examples

## p-values and Statistical Significance
* What and why?
* Correct interpretation
* Effect size
* How to report

## Confidence Intervals

## Further Reading

[**Statistics Kingdom**](https://www.statskingdom.com/index.html): Perform statistical tests online. The front page includes an extensive summary of statistical tests, their use, requirements, and assumptions. There is also a handy [Statistical Test Finder](https://www.statskingdom.com/statistical-decision-tree.html) that will help you select an appropriate test for your purpose.

[**An Introduction to Statistics: Choosing the Correct Statistical Test**](https://pmc.ncbi.nlm.nih.gov/articles/PMC8327789/), Ranganathan, P
